import { Parallax } from 'components'
import isEqual from 'fast-deep-equal'
import React from 'react'

const IntorContainer: React.FC = () => {
  return (
    <>
      {/* depth 1 */}

      <Parallax
        top="30%"
        right="37%"
        translateX="-30"
        translateY="-30"
        backgroundImage="/storybook.svg"
        width={'150px'}
        height={'150px'}
        zIndex={20}
      />
      <Parallax
        bottom="20%"
        left="25%"
        translateX="-30"
        translateY="-30"
        backgroundImage="/prisma.svg"
        width={'150px'}
        height={'150px'}
        zIndex={20}
      />
      <Parallax
        top="5%"
        left="5%"
        translateX="-30"
        translateY="-30"
        backgroundImage="/node.svg"
        width={'150px'}
        height={'150px'}
        zIndex={20}
      />
      <Parallax
        bottom="8%"
        right="7%"
        translateX="-30"
        translateY="-30"
        backgroundImage="/javascript.svg"
        width={'150px'}
        height={'150px'}
        zIndex={20}
      />
      <Parallax
        top="13%"
        right="13%"
        translateX="-30"
        translateY="-30"
        backgroundImage="/redux.svg"
        width={'150px'}
        height={'150px'}
        zIndex={10}
      />
      {/* --------------------------------------- */}
      {/* depth 2 */}
      <Parallax
        bottom="10%"
        left="10%"
        translateX="-20"
        translateY="-20"
        backgroundImage="/react.svg"
        width={'150px'}
        height={'150px'}
        blur={3}
        zIndex={10}
      />
      <Parallax
        top="36%"
        left="17%"
        translateX="-20"
        translateY="-20"
        backgroundImage="/vue.svg"
        width={'150px'}
        height={'150px'}
        blur={3}
        zIndex={10}
      />
      <Parallax
        top="32%"
        right="10%"
        translateX="-20"
        translateY="-20"
        backgroundImage="/html.svg"
        width={'150px'}
        height={'150px'}
        blur={3}
        zIndex={10}
      />
      <Parallax
        top="56%"
        right="23%"
        translateX="-20"
        translateY="-20"
        backgroundImage="/typescript.svg"
        width={'150px'}
        height={'150px'}
        blur={3}
        zIndex={10}
      />
      <Parallax
        top="10%"
        left="46%"
        translateX="-20"
        translateY="-20"
        backgroundImage="/graphql.svg"
        width={'150px'}
        height={'150px'}
        blur={3}
        zIndex={10}
      />
      {/* --------------------------------------- */}
      {/* depth 3 */}
      <Parallax
        top="16%"
        left="28%"
        translateX="-10"
        translateY="-10"
        backgroundImage="/mysql.svg"
        width={'150px'}
        height={'150px'}
        blur={5}
        zIndex={10}
      />
      <Parallax
        top="47%"
        left="5%"
        translateX="-10"
        translateY="-10"
        backgroundImage="/mobx.svg"
        width={'100px'}
        height={'100px'}
        blur={5}
        zIndex={10}
      />
      <Parallax
        bottom="42%"
        left="35%"
        translateX="-10"
        translateY="-10"
        backgroundImage="/docker.svg"
        width={'100px'}
        height={'100px'}
        blur={5}
        zIndex={10}
      />
      <Parallax
        bottom="17%"
        left="45%"
        translateX="-10"
        translateY="-10"
        backgroundImage="/css.svg"
        width={'150px'}
        height={'150px'}
        blur={5}
        zIndex={10}
      />
    </>
  )
}

export default React.memo(IntorContainer, isEqual)
