import { gsap } from 'gsap';
import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import styled from 'styled-components';
import { $Color } from '../styles/common';
import Introduce from './main/introduce';

const Main = styled.main`
  width: 100%;
  height: 100vh;
  background-color: ${$Color.default.dark4};
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
`;

const Title = styled.h1`
  width: 500px;
  height: 150px;
  background-color: #bfbfff;
  position: absolute;
  top: 150px;
  left: 150px;
  will-change: transform;
`;

const Year = styled.h2`
  width: 500px;
  height: 150px;
  background-color: ${$Color.default.bright4};
  position: absolute;
  top: 600px;
  right: 150px;
  will-change: transform;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Introduce />
    </div>
  );
};

export default Home;
