import type { NextPage } from 'next';
import Head from 'next/head';
import styled from 'styled-components';


const Main = styled.main`
  width: 100%;
  height: 100vh;
  background-color:#252538;
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
`
const LayoutCenter = styled.div`
  width: 300px;
  height: 300px;
  background-color: #6667ab;
`


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <LayoutCenter/>
      </Main>
    </div>
  )
}

export default Home
